# add c + bash?
#language: haskell
#ghc: 7.4
# php: 5.6
# node_js: 0.12

# https://github.com/koalaman/shellcheck/issues/589
addons:
  apt:
    sources:
    - debian-sid	# Grab shellcheck from the Debian repo
    packages:
    - shellcheck

# see http://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - bb@npl.de
#   - kontakt@weimarnetz.de

# installing 'sloccount' and 'shellcheck' needs sudo
# maybe we should switch to selfcompile these
# also '/etc/kalua_init' needs somehow root (e.g. mount)
sudo: required

# if one fails, the build is marked b0rken
script:
  - 'openwrt-build/build.sh --travis_prepare'
  - 'openwrt-build/build.sh --check'
  - 'openwrt-build/build.sh --unittest'
