# see http://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - bittorf@bluebottle.com
#   - kontakt@weimarnetz.de

# installing 'sloccount' and 'shellcheck' needs sudo
# maybe we should switch to selfcompile these
sudo: required

script: 'openwrt-build/build.sh --debug --check'
script: 'openwrt-build/build.sh --travis_prepare'
script: 'openwrt-build/build.sh --unittest'
